spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zhangtianyi
    password: zhangtianyi
    virtual-host: vhost_test01
    listener:
      simple: 
        prefetch: 10
        concurrency: 1
        acknowledge-mode: manual
        #retry:
          #max-attempts: 5
          #enabled: true
          #initial-interval: 5000
      
    
rabbitmq:
  requestQueue: requestQueue
  responseQueue: responseQueue
  requestExchange: requestExchange
  requestRoutingkey: request
  deadExchange: deadExchange
  deadQueue: deadQueue
  deadRoutingkey: dead
    
  
