server:
  port: 8011

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  cloud:
    stream:
      binders:
        litteRabbit:
          environment:
            spring:
              rabbitmq:
                addresses: 127.0.0.1:5672
                username: zhangtianyi
                password: zhangtianyi
                virtual-host: vhost_test01
          type: rabbit
      bindings:
        outputBusinessAdvice:
          binder: litteRabbit
          destination: businessAdviceDestination
        inputBusinessAdvice:
          binder: litteRabbit
          destination: businessAdviceDestination
          group: businessAdviceGroup
          consumer:
            # 最多尝试处理几次，默认3	
            maxAttempts: 5
      rabbit:
        bindings:
          inputBusinessAdvice:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              # 对顺序不做要求时
              # prefetch: 250
              # maxConcurrency: 5


      